# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('shows', '0005_show_social_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='sponsors',
            field=models.ManyToManyField(null=True, to='sponsors.Sponsor'),
        ),
    ]
